# Generated by Django 5.1.4 on 2026-05-28 16:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('match', models.CharField(choices=[('all', 'Todos'), ('any', 'Cualquiera')], default='all', max_length=10)),
                ('conditions', models.JSONField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='subscribers.subscriberlist'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='subscribers.subscriberlist')),
            ],
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('done', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('file_data', models.TextField()),
                ('total', models.IntegerField(default=0)),
                ('imported', models.IntegerField(default=0)),
                ('skipped', models.IntegerField(default=0)),
                ('errors', models.JSONField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='subscribers.subscriberlist'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='subscribers.subscriberlist')),
            ],
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.SlugField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('date', 'Fecha'), ('boolean', 'Booleano')], default='text', max_length=20)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='subscribers.subscriberlist')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('unsubscribed', 'Dado de baja'), ('bounced', 'Rebotado'), ('complained', 'Queja spam')], default='active', max_length=20)),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='subscribers.subscriberlist')),
            ],
            options={
                'ordering': ['-subscribed_at'],
                'unique_together': {('list', 'email')},
            },
        ),
    ]
