# Generated by Django 5.1.4 on 2026-05-28 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_remove_campaign_segment'),
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importjob',
            name='list',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='list',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='custom_data',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='ip_address',
        ),
        migrations.DeleteModel(
            name='CustomField',
        ),
        migrations.DeleteModel(
            name='ImportJob',
        ),
        migrations.DeleteModel(
            name='Segment',
        ),
    ]
