# Generated by Django 5.1.4 on 2026-05-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='from_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='from_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
