# Generated by Django 5.1.4 on 2026-05-28 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_from_email_alter_campaign_from_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='segment',
        ),
    ]
