# Generated by Django 5.1.4 on 2026-05-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_remove_campaign_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='ab_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='ab_split_percent',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='campaign',
            name='subject_b',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='campaignsend',
            name='ab_variant',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
    ]
