# Generated by Django 6.0.5 on 2026-05-28 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_ab_enabled_campaign_ab_split_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='ab_split_percent',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programada'), ('sending', 'Enviando'), ('sent', 'Enviada'), ('paused', 'Pausada'), ('failed', 'Fallida')], default='draft', max_length=20),
        ),
    ]
