# Generated by Django 6.0.5 on 2026-05-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_alter_campaign_ab_split_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='excluded_emails',
            field=models.TextField(blank=True, default=''),
        ),
    ]
