# Generated by Django 6.0.5 on 2026-05-28 20:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscribers', '0002_remove_importjob_list_remove_segment_list_and_more'),
        ('subscription_forms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation', to='subscription_forms.subscriptionform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='active', max_length=20)),
                ('last_step_sent', models.IntegerField(default=-1)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='automations.automation')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_enrollments', to='subscribers.subscriber')),
            ],
            options={
                'unique_together': {('automation', 'subscriber')},
            },
        ),
        migrations.CreateModel(
            name='AutomationStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('subject', models.CharField(max_length=250)),
                ('html_content', models.TextField()),
                ('delay_amount', models.PositiveIntegerField(default=0)),
                ('delay_unit', models.CharField(choices=[('hours', 'Horas'), ('days', 'Días')], default='days', max_length=10)),
                ('from_name', models.CharField(blank=True, max_length=150)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='automations.automation')),
            ],
            options={
                'ordering': ['order', 'delay_amount'],
            },
        ),
        migrations.CreateModel(
            name='AutomationSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sends', to='automations.automationenrollment')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automations.automationstep')),
            ],
            options={
                'unique_together': {('enrollment', 'step')},
            },
        ),
    ]
