# Generated by Django 6.0.5 on 2026-05-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationstep',
            name='delay_unit',
            field=models.CharField(choices=[('minutes', 'Minutos'), ('hours', 'Horas'), ('days', 'Días')], default='days', max_length=10),
        ),
    ]
