# Generated by Django 6.0.5 on 2026-05-28 20:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(default='Suscríbete a nuestra newsletter', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('button_text', models.CharField(default='Suscribirme', max_length=100)),
                ('success_message', models.CharField(default='¡Gracias! Revisa tu correo para confirmar la suscripción.', max_length=500)),
                ('redirect_url', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#4f46e5', max_length=7)),
                ('collect_first_name', models.BooleanField(default=True)),
                ('collect_last_name', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
