# Generated by Django 5.1.4 on 2026-05-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='smtp_port',
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name='user',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='smtp_user',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_provider',
            field=models.CharField(choices=[('local', 'Local (no envía)'), ('smtp_generic', 'SMTP genérico'), ('raiola', 'Raiola Networks'), ('gmail', 'Gmail'), ('outlook', 'Outlook / Office 365'), ('yahoo', 'Yahoo Mail'), ('icloud', 'iCloud Mail'), ('zoho', 'Zoho Mail'), ('hostinger', 'Hostinger'), ('ionos', 'IONOS'), ('ovh', 'OVH'), ('dondominio', 'DonDominio'), ('ses', 'Amazon SES (SMTP)'), ('mailgun', 'Mailgun (SMTP)'), ('postmark', 'Postmark (SMTP)'), ('mailjet', 'Mailjet (SMTP)'), ('sparkpost', 'SparkPost (SMTP)'), ('resend', 'Resend (SMTP)'), ('brevo', 'Brevo (API)'), ('sendgrid', 'SendGrid (API)')], default='local', max_length=20),
        ),
    ]
