# Generated by Django 5.1.4 on 2026-05-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_smtp_host_user_smtp_password_user_smtp_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='footer_address',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='footer_button_label',
            field=models.CharField(blank=True, default='Darse de baja', max_length=80),
        ),
        migrations.AddField(
            model_name='user',
            name='footer_company',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='footer_unsubscribe_text',
            field=models.CharField(blank=True, default='Si ya no quieres recibir nuestros correos, puedes darte de baja en cualquier momento.', max_length=300),
        ),
    ]
