# Generated by Django 6.0.5 on 2026-05-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_footer_address_user_footer_button_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='footer_forward_text',
            field=models.CharField(blank=True, default='Si te ha gustado este email, reenvíaselo a un compañero.', max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='footer_subscribe_text',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
