# Generated by Django 6.0.5 on 2026-05-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_footer_forward_text_user_footer_subscribe_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='send_rate_per_hour',
            field=models.PositiveIntegerField(default=300),
        ),
    ]
